
/* contruit N+1 points x0 ... xn*/
/* Distribution régulière*/
reglist(a,b,n):=block 
(
	l:[],	
	for i:0 thru n step 1 do
	(
		l:endcons(a+i*(b-a)/n,l)
	),
	l
)$

/* Distribution Tchebychev*/
tchebylist(a,b,n):=block
(
	l:[],
	for i:0 thru n step 1 do
	(
		l:endcons((a+b)/2-(b-a)/2*cos((i+1/2)*%pi/(n+1)),l)
	),
	l
)$


specreglist(a,b,n):=block 
(
	l:[],	
	for i:0 thru n-1 step 1 do
	(
		l:endcons(a+i*(b-a)/n,l)
	),
	l
)$


